### ISSUE TITLE
Jewelry: Bugged items

### ISSUE THREAD

**Issue by rsbfox** [rsbmatt/OSBuddy#131]
- Bugged
- [x] Amulet of glory(1)#1706
- [x] Digsite pendant (2)#11191
- [x] Digsite pendant (1)#11190 //Displaying 0 stack size.
- [x] Skills necklace(1)#11111
- [x] Combat bracelet(1)#11124
- [x] Games necklace(1)#3867
- [x] Ring of dueling(1)#2566
- [x] Ring of wealth (1)#11988
- [x] Abyssal bracelet(1)#11103
- [ ] "Show total charges" doubles when you equip some jewelry.
- [ ] Check binding necklace code. They only have 16 uses.
![image](https://user-images.githubusercontent.com/30416150/29132436-38eed9b8-7cfe-11e7-880a-6443adb23650.png)

**Comment by rsbfox** [comment]
Moved to Jira.
