### ISSUE TITLE
Bank Overlay: Items that need exchangeable values added

### ISSUE THREAD

**Issue by rsbfox** [rsbmatt/OSBuddy#22]
Item in bank -> item/s to get price from
-

- [x] Mark of grace#11849 -> 10 x Amylase crystal#12640 //You can trade these for amylase packs easily.
- [x] Tanzanite helm#13197 -> Serpentine helm (uncharged)#12929
- [x] Magma helm#13199 -> Serpentine helm (uncharged)#12929
- [x] Tanzanite helm (uncharged)#13196 -> Serpentine helm (uncharged)#12929
- [x] Magma helm (uncharged)#13198 -> Serpentine helm (uncharged)#12929
- Slayer helms
- [x] Red slayer helmet (i)#19649 -> Black mask#8921
- [x] Red slayer helmet#19647 -> Black mask#8921
- [x] Slayer helmet (i)#11865 -> Black mask#8921
- [x] Slayer helmet#11864 -> Black mask#8921
- [x] Black slayer helmet#19639 -> Black mask#8921
- [x] Black slayer helmet (i)#19641 -> Black mask#8921
- [x] Green slayer helmet#19643 -> Black mask#8921
- [x] Green slayer helmet (i)#19645 -> Black mask#8921
- [x] Purple slayer helmet#21264 -> Black mask#8921
- [x] Purple slayer helmet (i)#21266 -> Black mask#8921
- Removed the max capes after a second thought. Would not make sense logically with other plugins calling it an exchange value.

Every ornament in game. Some of these might already be done. Couldn't test. Sorry.
-
- Ornament kit - keep kit
- [x] Dragon full helm (g)#12417 -> Dragon full helm#11335 + Dragon full helm ornament kit#12538
- [x] Dragon chainbody (g)#12414 -> Dragon chainbody#3140 + Dragon chainbody ornament kit#12534
- [x] Dragon platelegs (g)#12415 -> Dragon platelegs#4087 + Dragon legs/skirt ornament kit#12536
- [x] Dragon plateskirt (g)#12416 -> Dragon plateskirt (g)#4585 + Dragon legs/skirt ornament kit#12536
- [x] Dragon sq shield (g)#12418 -> Dragon sq shield#1187 + Dragon sq shield ornament kit#12532
- [x] Dragon scimitar (or)#20000 -> Dragon scimitar#4587 + Dragon scimitar ornament kit#20002
- [x] Dragon defender (t)#19722 -> Dragon defender ornament kit#20143
- [x] Armadyl godsword (or)#20368 -> Armadyl godsword#11802 + Armadyl godsword ornament kit#20068
- [x] Bandos godsword (or)#20370 -> Bandos godsword#11804 + Bandos godsword ornament kit#20071
- [x] Saradomin godsword (or)#20372 -> Saradomin godsword#11806 + Saradomin godsword ornament kit#20074
- [x] Zamorak godsword (or)#20374 -> Zamorak godsword#11808 + Zamorak godsword ornament kit#20077
- [x] Dark infinity hat#12457 -> Infinity hat#6918 + Dark infinity colour kit#12528
- [x] Dark infinity top#12458 -> Infinity top#6916 + Dark infinity colour kit#12528
- [x] Dark infinity bottoms#12459 -> Infinity bottoms#6924 + Dark infinity colour kit#12528
- [x] Light infinity hat#12419 -> Infinity hat#6918 + Light infinity colour kit#12530
- [x] Light infinity top#12420 -> Infinity top#6916 + Light infinity colour kit#12530
- [x] Light infinity bottoms#12421 -> Infinity bottoms#6924 + Light infinity colour kit#12530
- [x] Amulet of fury (or)#12436 -> Amulet of fury#6585 + Fury ornament kit#12526
- [x] Amulet of torture (or)#20366 -> Amulet of torture#19553 + Torture ornament kit#20062
- [x] Occult necklace (or)#19720 -> Occult necklace#12002 + Occult ornament kit#20065
- Ornament kits - lose kit
- [x] Dark bow#12765 -> Dark bow#11235
- [x] Dark bow#12767 -> Dark bow#11235
- [x] Dark bow#12768 -> Dark bow#11235
- [x] Dark bow#12766 -> Dark bow#11235
- [x] Volcanic abyssal whip#12773 -> Abyssal whip#4151
- [x] Frozen abyssal whip#12774 -> Abyssal whip#4151
- [x] Granite maul#12848 -> Granite maul#4153
- [x] Steam battlestaff#12795 -> Steam battlestaff#11787
- [x] Lava battlestaff#21198 -> Lava battlestaff#3053
- [x] Dragon pickaxe#12797 -> Dragon pickaxe#11920
- [x] Odium ward#12807 -> Odium ward#11926
- [x] Malediction ward#12806 -> Malediction ward#11924
- Other bugs
- [x] Check overlay logic when set to exchange only. Should be showing value before alch if there is a value > 0.

Reply with items and I will add to list. Only suggest untradeable items that can be converted into something with value easily. Items like infernal tools can never be converted back to something that can be sold on ge. So while they had a cost, they don't have a value anymore.

**Comment by rsnjames** [comment]
Master Scroll Book should have a value when empty as well as when there are scrolls in it. Is it possible to have the value of the full book shown include the price of the scrolls?  By possibly opening the book could it grab what scrolls are in there and quantity and update the value of the book accordingly?

**Comment by rsbfox** [comment]
I will just add empty book to list. Filled book will need investigated. Thanks.

**Comment by rsbfox** [comment]
Master book will get a value when it's on exchange see: [#46](https://github.com/rsbmatt/OSBuddy/issues/46)

I don't think overlay can get items inside book.

**Comment by NoEffex** [comment]
Can partially be done now, partially later. We also need the ids for max capes.

Also, Tyrannical ring (i) and Berserker ring (i) appear to already have been added

**Comment by rsbfox** [comment]
Thanks @NoEffex 

Exchange
![image](https://user-images.githubusercontent.com/30416150/28680398-3a61acec-72c4-11e7-829d-cac08f101343.png)
Exchange and alch
![image](https://user-images.githubusercontent.com/30416150/28680458-68e88b94-72c4-11e7-9146-0d3ac7593138.png)
Logic bug there. It should show exchange value if market value > 0.

-----------------
![image](https://user-images.githubusercontent.com/30416150/28680548-b77fc39e-72c4-11e7-90d7-ae7cb0478afe.png)
Not sure what that one is. It's not even getting market value from non-(i) ring.

v3.0.12

I will get max cape ids.

**Comment by rsbfox** [comment]
Removed priority tags because issue has changed.

**Comment by rsbmatt** [comment]
Added all of the overrides that were on the list. Pushed to beta, v3.0.15.2

**Comment by rsbfox** [comment]
https://rsbuddy.com/osbuddy/patch_notes/3.0.16
