### ISSUE TITLE
Option Reorder: List of missing bankers

### ISSUE THREAD

**Issue by rsbfox** [rsbmatt/OSBuddy#6]
- [x] null#6521 Varrock west
- [x] null#6522 Varrock east
- [x] Magnus Gram#6512 Jatizso

v3.0.10.5

Will check more bankers. Keep open for now.

**Comment by rsbfox** [comment]
They are impostor npcs. Being looked into.

**Comment by rsbfox** [comment]
Fixed in v3.0.10.6

**Comment by rsbfox** [comment]
![screen shot 2017-07-26 at 9 51 56 am](https://user-images.githubusercontent.com/30416150/28624818-50778844-71e8-11e7-80fb-fe3c0f4bbcb5.png)
