### ISSUE TITLE
Slayer: Face mask not detected on purple slayer helmet

### ISSUE THREAD

**Issue by rsnjames** [rsbmatt/OSBuddy#71]
![bug](https://i.gyazo.com/df7a79dfed36b325fe5b768185d1dc08.png)

Unsure if it's just the purple slayer helm that has this issue or not. 

Osbuddy version 3.0.13

Scyther#7973 in discord reported this bug.

**Comment by rsbfox** [comment]
@rsnjames The prio-rity tags can only be used by rsbuddy staff. They are triage tags showing what rsbuddy has to work on first or what is just very easy for them to do. For an issue you want to wait to check other items like that you use pending-need more info.

prio-needs investigating means rsbuddy needs to investigate more before deciding on priority and/or how easy something will be to do.

I only added some yesterday because I was sent a list of what issues were what before I made those tags.

**Comment by rsbfox** [comment]
- All the recolored slayer helms.
- [x] Red slayer helmet (i)#19649
- [x] Red slayer helmet#19647
- [x] Slayer helmet (i)#11865
- [x] Slayer helmet#11864
- [x] Black slayer helmet#19639
- [x] Black slayer helmet (i)#19641
- [x] Green slayer helmet#19643
- [x] Green slayer helmet (i)#19645
- [x] Purple slayer helmet#21264
- [x] Purple slayer helmet (i)#21266
